language: java
sudo: false
jdk:
  - oraclejdk8
  - openjdk8
script:
  - mvn clean verify
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false