# Reference : 
# https://www.yegor256.com/2015/01/10/windows-appveyor-maven.html
# https://github.com/dblock/log4jna/blob/master/appveyor-mvn-release.yml
# https://www.appveyor.com/docs/appveyor-yml/
version: 1.0.{build}-{branch}
os: Visual Studio 2015
branches:
  only:
    - master
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.5.4\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - mvn clean verify
test_script:
  - mvn clean test
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2